# Generated by Django 5.0.4 on 2024-06-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombree', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Futbol', 'Futbol'), ('Software', 'Software'), ('Investigacion', 'Investigacion')], max_length=50)),
                ('alumno', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=300)),
            ],
        ),
    ]
